In [14]:
from retrieval import wav_to_rep
from models import SpecAutoEncoder
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# load model
model = SpecAutoEncoder()
model_name = "SpecAutoEncoder"

model.load_state_dict(torch.load("../models" + f"/{model_name}_best.pt"))
model.to(device)

wav_file_path = r"E:\cs682\data\fma_small_wav\000002.wav"
rep = wav_to_rep(wav_file_path, model, device)
print(rep)

tensor([[[[0.9153, 0.7772, 0.1399,  ..., 0.5501, 0.1315, 0.1921],
          [0.7624, 0.9413, 0.3713,  ..., 1.2966, 0.6611, 0.7258],
          [1.0942, 0.9011, 0.4540,  ..., 1.1809, 0.4865, 0.2040],
          ...,
          [0.9175, 0.8859, 0.2485,  ..., 1.0738, 0.8738, 0.7553],
          [1.2501, 0.7130, 1.0078,  ..., 1.1086, 0.6304, 1.2504],
          [0.9327, 0.9566, 0.8799,  ..., 0.7230, 0.8107, 1.2864]],

         [[0.0451, 0.5539, 0.1480,  ..., 1.1895, 0.4677, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.2602, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.4219, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.5418, 0.7950, 0.0000,  ..., 0.3962, 0.0770, 0.7439],
          [0.8693, 1.4970, 0.5054,  ..., 1.0945, 0.3136, 1.1813],
          [1.0784, 1.2374, 0.5356,  ..., 1

In [2]:
import numpy as np

In [15]:
db = torch.from_numpy(np.load("../data/database.npy"))

In [16]:
db = db.to(device)
print(rep.shape)
print(db.shape)
db = db.flatten(start_dim=1)
rep = rep.flatten(start_dim=1)
a_norm = db / db.norm(dim=1)[:, None]
b_norm = rep / rep.norm(dim=1)[:, None]

res = torch.mm(a_norm, b_norm.transpose(0,1))
print(res)

torch.Size([1, 64, 32, 64])
torch.Size([1600, 64, 32, 64])
tensor([[0.5335],
        [0.5328],
        [0.5736],
        ...,
        [0.4828],
        [0.5508],
        [0.5444]], device='cuda:0')


In [34]:
# read json file
import json
import os


with open("../data/tensor_ids.json", "r") as f:
    data = json.load(f)

data

['000010',
 '000010',
 '000182',
 '000182',
 '000204',
 '000204',
 '000459',
 '000459',
 '000546',
 '000546',
 '000708',
 '000708',
 '000718',
 '000718',
 '000853',
 '000853',
 '001087',
 '001087',
 '001270',
 '001270',
 '001427',
 '001427',
 '001644',
 '001644',
 '001687',
 '001687',
 '001701',
 '001701',
 '001702',
 '001702',
 '001736',
 '001736',
 '003273',
 '003273',
 '003537',
 '003537',
 '003573',
 '003573',
 '003833',
 '003833',
 '003904',
 '003904',
 '003909',
 '003909',
 '003910',
 '003910',
 '004076',
 '004076',
 '004103',
 '004103',
 '004108',
 '004108',
 '004239',
 '004239',
 '004685',
 '004685',
 '004782',
 '004782',
 '004835',
 '004835',
 '005158',
 '005158',
 '005264',
 '005264',
 '005381',
 '005381',
 '005521',
 '005521',
 '006331',
 '006331',
 '006333',
 '006333',
 '006440',
 '006440',
 '006463',
 '006463',
 '006603',
 '006603',
 '006856',
 '006856',
 '007375',
 '007375',
 '007383',
 '007383',
 '007386',
 '007386',
 '007391',
 '007391',
 '007482',
 '007482',
 '007489',

In [24]:
# convert to int tensor
tensor_ids = [int(i) for i in data]
tensor_ids = np.array(tensor_ids)

In [25]:
tensor_ids = tensor_ids.reshape(-1, 2)[:,:1]

In [27]:
tensor_ids = tensor_ids.flatten()

In [28]:
np.save("../data/tensor_ids.npy", tensor_ids)

In [29]:
db = np.load("../data/database.npy")


In [30]:
db.shape

(1600, 64, 32, 64)

In [33]:
db[3]

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [1.2826085 , 0.6590885 , 1.0795512 , ..., 1.3488721 ,
         0.6456839 , 0.99413884],
        [0.75374675, 0.14105208, 0.7073533 , ..., 0.41935173,
         0.96980834, 0.804788  ],
        [0.71641904, 1.0809457 , 0.656541  , ..., 0.8023146 ,
         0.78296405, 0.799667  ]],

       [[0.        , 0.52771324, 0.683431  , ..., 0.59734315,
         0.5230082 , 0.7284701 ],
        [0.        , 1.2020289 , 1.4481525 , ..., 1.3445848 ,
         1.4296623 , 1.3824066 ],
        [0.        , 1.4188563 , 1.4068838 , ..., 1.3920169 ,
         1.3987315 , 1.3738455 ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [32]:
db[2]

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [1.3060778 , 1.140469  , 1.5510821 , ..., 1.3776382 ,
         0.74290305, 0.846043  ],
        [0.7934479 , 0.62710774, 0.929273  , ..., 1.1876795 ,
         0.5624731 , 0.7201405 ],
        [0.8912358 , 1.5717216 , 0.5575187 , ..., 0.19171841,
         1.0153131 , 1.0534189 ]],

       [[0.        , 0.19208701, 0.44627294, ..., 0.5972185 ,
         0.7699447 , 0.43490177],
        [0.        , 0.7519051 , 1.0084083 , ..., 1.6126646 ,
         1.3167125 , 1.2434039 ],
        [0.        , 1.1628752 , 0.92266774, ..., 1.5139104 ,
         1.3306445 , 1.5348566 ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 